version: '3.7'
services:
  nodered:
    image: nodered/node-red:latest
    volumes:
      - ./data/nodered:/data
    ports:
      - '1880:1880'
    restart: always

  backup:
    build: .
    environment:
      GITHUB_REPO: "vchrombie/floodnet-nodered"
      GITHUB_BRANCH: "nodered-backup"
      GIT_USER_NAME: "github-actions[bot]"
      GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
      GIT_SRC: "/data/nodered"
      GITHUB_USERNAME: $GITHUB_USERNAME
      GITHUB_ACCESS_TOKEN: $GITHUB_ACCESS_TOKEN
      FILES_TO_COMMIT: >
        lib/
        flows.json
        .flows.json.backup
        .config.nodes.json
      COMMIT_MSG: "Backup nodered"
      PRE_BACKUP_SCRIPT: >
        echo 'This is a pre-backup script';
        echo 'This is another pre-backup script';
      BACKUP_FREQUENCY: "0 5 * * *"
    volumes:
      - ./data:/data
    restart: unless-stopped

volumes:
  nodered_backup:
    driver: local
